package:
  name: oce
  version: V7_5_0u

source:
  git_rev: tags/upstream/V7_5_0
  git_url: https://github.com/tpaviot/oce.git

requirements:
  build:
    - cmake
    - python
    - vtk
  run:
    - python
    - vtk

build:
  number: 0

about:
  home: https://github.com/tpaviot/oce
  license: LGPL2
  summary: OpenCASCADE Community Edition. This conda package builds OCE against VTK 9.10, Python 3.5 and Qt4.
